CREATE TABLE IF NOT EXISTS "LIQUIDACION_ON_US" (
    "ID_LIQUIDACION" UUID PRIMARY KEY,
    "ID_EVENTO_ORIGEN" UUID NOT NULL,
    "ID_LOTE" UUID NOT NULL,
    "ID_LINEA" UUID NOT NULL UNIQUE,
    "ID_CORRELACION" UUID NOT NULL,
    "NUMERO_SECUENCIA" INTEGER,
    "RUC_EMPRESA" VARCHAR(20),
    "NUMERO_CUENTA_MATRIZ" VARCHAR(40),
    "ID_FONDEO_CORE" VARCHAR(80) NOT NULL,
    "IDENTIFICACION_BENEFICIARIO" VARCHAR(30) NOT NULL,
    "NOMBRE_BENEFICIARIO" VARCHAR(120) NOT NULL,
    "NUMERO_CUENTA_DESTINO" VARCHAR(40) NOT NULL,
    "CODIGO_ENRUTAMIENTO" VARCHAR(10) NOT NULL,
    "NOMBRE_INSTITUCION_DESTINO" VARCHAR(120),
    "MONTO" NUMERIC(18, 2) NOT NULL,
    "MONEDA" VARCHAR(3) NOT NULL,
    "REFERENCIA" VARCHAR(140),
    "EMAIL_NOTIFICACION" VARCHAR(120),
    "ESTADO" VARCHAR(40) NOT NULL,
    "COBRABLE" BOOLEAN NOT NULL,
    "CLAVE_IDEMPOTENCIA" VARCHAR(80) NOT NULL,
    "ID_TRANSACCION_CORE" VARCHAR(80),
    "FECHA_CONTABLE" DATE,
    "CODIGO_RECHAZO" VARCHAR(80),
    "MOTIVO_RECHAZO" VARCHAR(500),
    "FECHA_CREACION" TIMESTAMPTZ NOT NULL,
    "FECHA_ACTUALIZACION" TIMESTAMPTZ NOT NULL,
    "FECHA_FINALIZACION" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "INTENTO_LIQUIDACION_ON_US" (
    "ID_INTENTO" UUID PRIMARY KEY,
    "ID_LIQUIDACION" UUID NOT NULL,
    "ID_LOTE" UUID NOT NULL,
    "ID_LINEA" UUID NOT NULL,
    "NUMERO_INTENTO" INTEGER NOT NULL,
    "FECHA_SOLICITUD" TIMESTAMPTZ NOT NULL,
    "FECHA_RESPUESTA" TIMESTAMPTZ,
    "ESTADO_INTENTO" VARCHAR(40) NOT NULL,
    "ESTADO_CORE" VARCHAR(40),
    "ID_TRANSACCION_CORE" VARCHAR(80),
    "FECHA_CONTABLE" DATE,
    "CODIGO_ERROR" VARCHAR(80),
    "MENSAJE_ERROR" VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS "IDX_LIQUIDACION_ON_US_LOTE"
    ON "LIQUIDACION_ON_US" ("ID_LOTE");

CREATE INDEX IF NOT EXISTS "IDX_LIQUIDACION_ON_US_ESTADO"
    ON "LIQUIDACION_ON_US" ("ESTADO");

CREATE INDEX IF NOT EXISTS "IDX_INTENTO_LIQUIDACION_LINEA"
    ON "INTENTO_LIQUIDACION_ON_US" ("ID_LINEA");

CREATE INDEX IF NOT EXISTS "IDX_INTENTO_LIQUIDACION"
    ON "INTENTO_LIQUIDACION_ON_US" ("ID_LIQUIDACION");
